# Generated by Django 5.2 on 2025-04-18 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('carnet', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('movil', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('seleccion_grado', models.CharField(choices=[('grado1', 'Ninguno'), ('grado2', 'Noveno Grado'), ('grado3', 'Bachiller'), ('grado4', 'Superior')], default='grado1', max_length=12)),
                ('seleccion_ocupacion', models.CharField(choices=[('ocupacion1', 'Desocupado'), ('ocupacion2', 'Ama de Casa'), ('ocupacion3', 'Trabajador Estatal'), ('ocupacion4', 'Trabajador por Cuenta Propia')], default='ocupacion1', max_length=12)),
                ('titulo', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(code='correo_invalido', message='El Correo debe ser finalizado en .com', regex='\\.com$')])),
            ],
        ),
    ]
