# Generated by Django 5.2 on 2025-04-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='direccion',
            new_name='dirección',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='seleccion_grado',
            new_name='grado',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='movil',
            new_name='móvil',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='seleccion_ocupacion',
            new_name='ocupación',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='telefono',
            new_name='teléfono',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='titulo',
            new_name='título',
        ),
        migrations.AlterField(
            model_name='registro',
            name='carnet',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='registro',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=12),
        ),
    ]
