# Generated by Django 5.2 on 2025-04-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_rename_direccion_registro_dirección_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='grado',
            field=models.CharField(choices=[('Ninguno', 'Ninguno'), ('Noveno Grado', 'Noveno Grado'), ('Bachiller', 'Bachiller'), ('Superior', 'Superior')], default='Ninguno', max_length=100),
        ),
        migrations.AlterField(
            model_name='registro',
            name='ocupación',
            field=models.CharField(choices=[('Desocupado', 'Desocupado'), ('Ama de Casa', 'Ama de Casa'), ('Trabajador Estatal', 'Trabajador Estatal'), ('Trabajador por Cuenta Propia', 'Trabajador por Cuenta Propia')], default='Desocupado', max_length=100),
        ),
    ]
