# Generated by Django 5.2 on 2025-04-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_registro_grado_alter_registro_ocupación'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='dirección',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='móvil',
            new_name='movil',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='teléfono',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='título',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='ocupación',
        ),
        migrations.AddField(
            model_name='registro',
            name='ocupacion',
            field=models.CharField(choices=[('ocupacion1', 'Desocupado'), ('ocupacion2', 'Ama de Casa'), ('ocupacion3', 'Trabajador Estatal'), ('ocupacion4', 'Trabajador por Cuenta Propia')], default='ocupacion1', max_length=12),
        ),
        migrations.AlterField(
            model_name='registro',
            name='grado',
            field=models.CharField(choices=[('grado1', 'Ninguno'), ('grado2', 'Noveno Grado'), ('grado3', 'Bachiller'), ('grado4', 'Superior')], default='grado1', max_length=12),
        ),
    ]
