# Generated by Django 5.2 on 2025-04-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_alter_registro_ocupacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='ocupacion',
            field=models.CharField(choices=[('ocupacion1', 'Desocupado'), ('ocupacion2', 'Ama de Casa'), ('ocupacion3', 'Trabajador Estatal'), ('ocupacion4', 'Trabajador por Cuenta Propia')], default='ocupacion1', max_length=100),
        ),
    ]
