# Generated by Django 5.2 on 2025-04-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_alter_registro_ocupacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='grado',
            field=models.CharField(choices=[('grado1', 'Ninguno'), ('grado2', 'Noveno Grado'), ('grado3', 'Bachiller'), ('grado4', 'Superior')], default='grado1', max_length=50),
        ),
        migrations.AlterField(
            model_name='registro',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
        ),
    ]
