# Generated by Django 5.2 on 2025-04-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_alter_registro_grado_alter_registro_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
