# Generated by Django 5.2 on 2025-04-27 21:22

import registro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_registro_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='carnet',
            field=models.CharField(max_length=11, validators=[registro.models.validar_carnet_unico]),
        ),
    ]
