# Generated by Django 5.2 on 2025-04-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_alter_registro_carnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='carnet',
            field=models.CharField(max_length=11),
        ),
    ]
