# Generated by Django 5.2 on 2025-04-27 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0012_alter_registro_carnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='carnet',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='carnet_invalido', message='El carnet debe tener exactamente 11 caracteres.', regex='^.{11}$')]),
        ),
    ]
